# Generated by Django 5.0.3 on 2024-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200, null=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("country", models.CharField(default="", max_length=50)),
                ("city", models.CharField(default="", max_length=80)),
                ("price", models.PositiveBigIntegerField()),
                (
                    "number_of_rooms",
                    models.PositiveBigIntegerField(verbose_name="rooms"),
                ),
                ("bathrooms", models.PositiveBigIntegerField()),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=250)),
                ("pet_allowed", models.BooleanField(default=False)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("entire_place", "Entire Place"),
                            ("private_room", "Private Room"),
                            ("shared_room", "Shared Room"),
                        ],
                        max_length=30,
                        verbose_name="room type",
                    ),
                ),
                ("amenities", models.ManyToManyField(to="rooms.amenity")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
