# Generated by Django 5.0.3 on 2024-04-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_amenity_options_alter_amenity_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="owner",
            new_name="host",
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
