# Generated by Django 5.0.3 on 2024-04-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("rooms", "0004_rename_owner_room_host_alter_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
    ]
