# Generated by Django 5.0.3 on 2024-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_room_amenities_alter_room_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="categories",
            new_name="category",
        ),
    ]
