# Generated by Django 5.0.3 on 2024-04-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_rename_categories_room_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="bathrooms",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="number_of_rooms",
            field=models.PositiveIntegerField(verbose_name="rooms"),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
