# Generated by Django 5.0.3 on 2024-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_alter_room_bathrooms_alter_room_number_of_rooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="max_capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
