# Generated by Django 5.0.3 on 2024-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_rename_experiences_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="city",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AddField(
            model_name="experience",
            name="country",
            field=models.CharField(default="", max_length=50),
        ),
    ]
