# Generated by Django 5.0.3 on 2024-04-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("experiences", "0003_experience_city_experience_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
            ),
        ),
        migrations.AlterField(
            model_name="includeditem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="includeditem",
            name="details",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
