# Generated by Django 5.0.3 on 2024-05-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_options_rename_type_category_kind"),
        (
            "experiences",
            "0004_experience_categories_alter_includeditem_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="categories",
        ),
        migrations.AddField(
            model_name="experience",
            name="categories",
            field=models.ManyToManyField(to="categories.category"),
        ),
    ]
