# Generated by Django 5.0.3 on 2024-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0007_rename_includeditem_inclusion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
