# Generated by Django 5.0.3 on 2024-07-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0008_alter_experience_end_time_and_more"),
        ("media", "0004_alter_video_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="thumnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="thumnail",
                to="media.photo",
            ),
        ),
    ]
