# Generated by Django 5.0.3 on 2024-04-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="type",
            new_name="kind",
        ),
    ]
