# Generated by Django 5.0.3 on 2024-04-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="kind",
            field=models.CharField(
                choices=[("room", "Room"), ("experience", "Experience")],
                default="room",
                max_length=14,
            ),
        ),
    ]
