# Generated by Django 5.0.3 on 2024-07-17 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_approval_status_booking_is_cancelled"),
        ("experiences", "0012_experience_end_date_experience_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="experience",
        ),
        migrations.AddField(
            model_name="booking",
            name="experience_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="experiences.experiencesession",
            ),
        ),
    ]
